# Generated by Django 3.1.2 on 2020-11-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0003_auto_20201104_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment_info.course'),
        ),
    ]
