# Generated by Django 3.1.2 on 2020-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0004_submissions_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
